name: CI/CD Pipeline - Product API (AWS)

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: apimrp

jobs:
  # STAGE 1 & 2: Build & Test (.NET 8)
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependencias
        run: dotnet restore src/API/ApiMRP.csproj

      - name: Compilar aplicación
        run: dotnet build src/API/ApiMRP.csproj --configuration Release --no-restore

      - name: Ejecutar Pruebas Unitarias
        run: |
          dotnet test --configuration Release --no-build --verbosity normal || echo "No se encontraron pruebas para ejecutar."

  # STAGE 3 & 4: Docker Build & Push to Amazon ECR
  docker-build-and-push:
    name: 🐳 Docker Build & Push to AWS ECR
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # 1. Autenticación en AWS mediante Secrets
      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 2. Login automático en Amazon ECR
      - name: Autenticación en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Build y Push de la imagen a Amazon ECR
      - name: Construir, etiquetar y publicar imagen Docker
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Compilar imagen localmente
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          
          # Subir etiquetas a ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  # 
  # STAGE 5: Deployment a AWS ECS
  deploy:
    name: 🚀 Automatic Deploy
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Despliegue en AWS
        run: |
          echo "Imagen lista en Amazon ECR para despliegue automático."
          echo "Servicio objetivo: AWS ECS / Fargate"